version: '3.7'
services:
  stash:
    image: stashapp/stash:latest
    container_name: stash
    restart: unless-stopped
    ## the container's port must be the same with the STASH_PORT in the environment section
    ports:
      - "9999:9999"
    ## If you intend to use stash's DLNA functionality uncomment the below network mode and comment out the above ports section
    # network_mode: host
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "2m"
    environment:
      - STASH_STASH=/data/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      ## Adjust below to change default port (9999)
      - STASH_PORT=9999
    volumes:
      - /etc/localtime:/etc/localtime:ro
      ## Adjust below paths (the left part) to your liking.
      ## E.g. you can change ./config:/root/.stash to ./stash:/root/.stash

      ## Keep configs, scrapers, and plugins here.
      - /home/umbrel/umbrel/my-configs/stash-config/stash:/root/.stash
      ## Point this at your collection.
      - /home/umbrel/umbrel/data/storage/Prn:/data
      ## This is where your stash's metadata lives
      - /home/umbrel/umbrel/my-configs/stash-config/metadata:/metadata
      ## Any other cache content.
      - /home/umbrel/umbrel/my-configs/stash-config/cache:/cache
      ## Where to store binary blob data (scene covers, images)
      - /home/umbrel/umbrel/my-configs/stash-config/blobs:/blobs
      ## Where to store generated content (screenshots,previews,transcodes,sprites)
      - /home/umbrel/umbrel/my-configs/stash-config/generated:/generated